export const categories = [
  {
    id: 1,
    name: 'Entertainment',
    description: 'description...',
    iconMaterial: 'emoji-emotions',
    iconMaterialCommunity: '',
  },
  {
    id: 2,
    name: 'Education',
    description: 'description...',
    iconMaterial: 'book',
    iconMaterialCommunity: '',
  },
  {
    id: 3,
    name: 'Sports',
    description: 'description...',
    iconMaterial: 'directions-bike',
    iconMaterialCommunity: '',
  },
  {
    id: 4,
    name: 'Restaurant',
    description: 'description...',
    iconMaterial: 'restaurant',
    iconMaterialCommunity: '',
  },
  {
    id: 5,
    name: 'Games',
    description: 'description...',
    iconMaterial: 'videogame-asset',
    iconMaterialCommunity: '',
  },
];

export const getCategoriesById = [
  {
    key: Math.random().toString(),
    categoryId: 3,
    iconMaterial: 'directions-bike',
    iconMaterialCommunity: '',
    name: 'Ride in the mountain',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 2,
    iconMaterial: 'book',
    iconMaterialCommunity: '',
    name: 'Workshop MQTT',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 2,
    iconMaterial: 'book',
    iconMaterialCommunity: '',
    name: 'Workshop with React for beginners',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 3,
    iconMaterial: '',
    iconMaterialCommunity: 'hiking',
    name: 'Hike in the mountain',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop with React for beginners',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop MQTT',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop with React for beginners',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop MQTT',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop with React for beginners',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop MQTT',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop with React for beginners',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop MQTT',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop with React for beginners',
    description: 'description...',
  },
  {
    key: Math.random().toString(),
    categoryId: 'Tech',
    iconMaterial: '',
    iconMaterialCommunity: '',
    name: 'Workshop MQTT',
    description: 'description...',
  },
];
